In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rc('font', family='NanumBarunGothic')
plt.rcParams['axes.unicode_minus']=False
data = pd.read_csv("C:/djangogirls/data/3dieases_People.csv",engine="python")
data.head()

,성별코드,연령대코드(5세단위),허리둘레,시력(좌),시력(우),수축기혈압,이완기혈압,식전혈당(공복혈당),총콜레스테롤,트리글리세라이드,...,고혈압위험도(이완),zy1,zy2,zy3,zy4,이상지질혈증 위험도(총콜),이상지질혈증 위험도(트리),이상지질혈증 위험도(HDL),이상지질혈증 위험도(LDL),이상지질혈증 위험도
0,2,13,57,0,0,130,70,101,220,153,...,-45.750,193.048,86.683,62.458,112.904,-17.381,-126.634,-12.288,21.506,21.506
1,2,15,61,0,0,142,79,123,168,88,...,-97.752,189.048,89.949,64.597,106.146,-27.380,-120.103,-22.987,10.243,10.243
2,2,11,61,0,0,131,77,109,203,174,...,-85.797,189.598,81.773,66.038,106.965,-26.006,-136.455,-30.191,11.608,11.608
3,2,7,62,0,0,128,89,104,148,168,...,-94.786,196.635,100.934,67.292,109.019,-8.413,-98.131,-36.458,15.031,15.031
4,2,16,63,0,0,96,64,102,190,162,...,-73.150,189.389,80.809,61.660,111.153,-26.528,-138.382,-8.298,18.589,18.589

In [19]:
data1 = data.iloc[:,-5:]
print(data1)

       이상지질혈증 위험도(총콜)  이상지질혈증 위험도(트리)  이상지질혈증 위험도(HDL)  이상지질혈증 위험도(LDL)  \
0             -17.381        -126.634          -12.288           21.506
1             -27.380        -120.103          -22.987           10.243
2             -26.006        -136.455          -30.191           11.608
3              -8.413         -98.131          -36.458           15.031
4             -26.528        -138.382           -8.298           18.589
5              -7.266        -117.881           -8.949           27.831
6             -18.182        -123.156          -21.145           17.529
7              -9.833        -101.720           -9.473           23.289
8             -39.317        -155.776          -13.229           11.578
9              -9.010        -113.246          -17.276           23.266
10            -19.419        -117.384          -21.760           15.631
11             -4.837        -101.074          -16.769           24.264
12            -10.854         -96.856           -3.193           23.861
13            -21.140        -117.814           -4.157           20.283
14            -10.018        -121.040          -33.374           18.720
15              5.609        -101.662          -21.392           29.708
16            -23.966         -65.850            0.998           12.019
17             -5.670        -108.078          -21.295           23.356
18            -45.633         -96.446           18.820            8.569
19            -39.944        -118.467           -5.330            7.553
20            -26.828        -125.715          -29.105            9.480
21            -18.043        -117.832          -21.988           16.632
22            -35.958         -86.260           -0.162            7.058
23             -9.100        -103.861          -20.255           20.853
24            -22.347        -123.510          -27.988           12.813
25            -15.854        -109.307           -6.428           21.622
26            -23.677        -113.197          -18.782           13.158
27             -8.720        -102.466          -15.072           22.458
28            -11.347        -102.431          -11.182           22.075
29            -35.848        -135.379          -16.856            9.506
...               ...             ...              ...              ...
50919         -14.226         -74.056           21.532           26.376
50920          -6.018         -60.885           23.499           29.982
50921          15.757         -27.596           36.022           43.417
50922         -10.353         -24.873           50.571           30.579
50923         -18.945         -84.583           10.544           21.256
50924           9.353           3.575           61.087           42.392
50925         -25.492         -83.691            5.427           14.844
50926          14.557          -9.714           38.281           40.433
50927          -7.140         -64.209           15.010           27.141
50928          17.358         -50.291            7.644           38.470
50929           2.439         -96.644            3.738           34.921
50930          -1.392         -17.259           47.149           33.935
50931          -1.752         -39.571           28.611           31.232
50932          -5.036         -50.067           23.937           29.445
50933         -12.968         -29.670           -0.776           12.635
50934          -2.670         -68.372            9.379           28.987
50935          -2.370         -90.067            2.666           30.588
50936           8.452          -9.087           38.457           36.296
50937         -15.839        -133.474          -28.607           18.369
50938          -0.831         -54.103           23.407           32.446
50939          14.484         -24.780           32.723           40.920
50940          -4.003         -55.968           16.713           28.161
50941         -17.802         -94.582           -4.602           18.513
50942          -0.900         -47.818           17.104           29.391
50943          -1.730         -59.606           14.291           29.715
50944          11.824         -29.306           28.407           38.462
50945         -22.680         -70.439           22.125           20.312
50946         -10.018         -46.381           31.930           28.199
50947          -3.832         -38.244           40.586           33.603
50948         -14.774         -71.647           12.898           22.573

       이상지질혈증 위험도
0          21.506
1          10.243
2          11.608
3          15.031
4          18.589
5          27.831
6          17.529
7          23.289
8          11.578
9          23.266
10         15.631
11         24.264
12         23.861
13         20.283
14         18.720
15         29.708
16         12.019
17         23.356
18         18.820
19          7.553
20          9.480
21         16.632
22          7.058
23         20.853
24         12.813
25         21.622
26         13.158
27         22.458
28         22.075
29          9.506
...           ...
50919      26.376
50920      29.982
50921      43.417
50922      50.571
50923      21.256
50924      61.087
50925      14.844
50926      40.433
50927      27.141
50928      38.470
50929      34.921
50930      47.149
50931      31.232
50932      29.445
50933      12.635
50934      28.987
50935      30.588
50936      38.457
50937      18.369
50938      32.446
50939      40.920
50940      28.161
50941      18.513
50942      29.391
50943      29.715
50944      38.462
50945      22.125
50946      31.930
50947      40.586
50948      22.573

[50949 rows x 5 columns]

In [22]:
print(data1['이상지질혈증 위험도(총콜)'][0])
print(data1['이상지질혈증 위험도(트리)'][0])
print(data1['이상지질혈증 위험도(HDL)'][0])
print(data1['이상지질혈증 위험도(LDL)'][0])
print(data1['이상지질혈증 위험도'][0])

-17.381
-120.103
-30.191
15.030999999999999
18.589000000000002